People_Power/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using People_Power.Interfaces;
using People_Power.Models;
using People_Power.ViewModel;
using System.Security.Claims;

namespace People_Power.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IPasswordHasher _passwordHasher;

        public AuthController(IUserRepository userRepository, IPasswordHasher passwordHasher)
        {
            _userRepository = userRepository;
            _passwordHasher = passwordHasher;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Check if the email is already registered
                if (await _userRepository.IsEmailExistsAsync(model.Email))
                {
                    ModelState.AddModelError("", "Email is already in use.");
                    return View(model);
                }

                if (await _userRepository.IsUserNameExistsAsync(model.UserName))
                {
                    ModelState.AddModelError("", "Username is already in use.");
                    return View(model);
                }

                // Create a new user
                var user = new User
                {
                    UserName = model.UserName,
                    Email = model.Email,
                    PasswordHash = _passwordHasher.HashPassword(model.Password),
                    RoleId = 2
                };

                // Save user to the database
                var result = await _userRepository.CreateUserAsync(user);

                if (result)
                {
                    TempData["SuccessMessage"] = "Registration successful! Please log in.";
                    return RedirectToAction("Login");
                }

                ModelState.AddModelError("", "An error occurred while registering. Please try again.");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Login() => View();

        [HttpPost]
        public async Task<IActionResult> Login(string email, string password)
        {
            var user = await _userRepository.GetUserByEmailAsync(email);
            var Passhash = _passwordHasher.HashPassword(password);
            if (user == null && user.PasswordHash != Passhash)
            {
                ViewBag.Message = "Invalid email or password.";
                return View();
            }
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.UserName),
                new Claim(ClaimTypes.Role, user.Role.Name)
            };
            var identity = new ClaimsIdentity(claims, "CookieAuth");
            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync("CookieAuth", principal);
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync("CookieAuth");
            return RedirectToAction("Login");
        }
        public IActionResult AccessDenied() => View();
    }
}

People_Power/Controllers/LeaveController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using People_Power.Data;
using People_Power.Interfaces;
using People_Power.Models;

namespace People_Power.Controllers
{
    public class LeaveController : Controller
    {
        private readonly ILeaveRepository _leaveRepository;
        private readonly AppDbContext _context;
        public LeaveController(ILeaveRepository leaveRepository, AppDbContext context)
        {
            _leaveRepository = leaveRepository;
            _context = context;
        }
        public async Task<IActionResult> LeaveList()
        {
            var leaves = await _leaveRepository.GetAllAsync();
            var employees = _leaveRepository.GetEmployees();
            var users = _leaveRepository.GetUsers();
            return View(leaves);
        }
        public async Task<IActionResult> LeaveListByID(int id)
        {
            var leave = await _leaveRepository.GetByIdAsync(id);
            if (leave == null)
            {
                return NotFound();
            }
            return View(leave);
        }
        [HttpGet]
        public async Task <IActionResult> CreateLeave()
        {
            var employees = _leaveRepository.GetEmployees();
            var users = _leaveRepository.GetUsers();

            ViewBag.Employees = new SelectList(employees, "Id", "Name");
            ViewBag.Users = new SelectList(users, "Id", "UserName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateLeave(Leave leave)
        {            
            if (ModelState.IsValid)
            {
                await _leaveRepository.AddAsync(leave);
                return RedirectToAction(nameof(LeaveList));
            }
            return View(leave);
        }
        public async Task<IActionResult> EditLeave(int id)
        {
            var leave = await _leaveRepository.GetByIdAsync(id);
            if (leave == null)
            {
                return NotFound();
            }
            var employees = _leaveRepository.GetEmployees();
            var users = _leaveRepository.GetUsers();

            ViewBag.Employees = new SelectList(employees, "Id", "Name");
            ViewBag.Users = new SelectList(users, "Id", "UserName");
            return View(leave);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditLeave(int id, Leave leave)
        {
            if (id != leave.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                     _leaveRepository.Update(leave);
                }
                catch (DbUpdateConcurrencyException)
                {
                    NotFound();
                }
                var employees = _leaveRepository.GetEmployees();
                var users = _leaveRepository.GetUsers();

                ViewBag.Employees = new SelectList(employees, "Id", "Name");
                ViewBag.Users = new SelectList(users, "Id", "UserName");
                return RedirectToAction(nameof(LeaveList));
            }
            return View(leave);
        }        
        public async Task<IActionResult> DeleteLeave(int id)
        {
            var leave = await _leaveRepository.GetByIdAsync(id);
            var users = _leaveRepository.GetUsers();
            var employees = _leaveRepository.GetEmployees();
            if (leave == null)
            {
                return NotFound();
            }
            return View(leave);
        }

        [HttpPost, ActionName("DeleteLeave")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteLeaveConfirmed(int id)
        {
            var leave = await _leaveRepository.GetByIdAsync(id);
            _leaveRepository.Delete(leave);
            return RedirectToAction(nameof(LeaveList));
        }
    }
}

People_Power/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using People_Power.Interfaces;
using People_Power.Models;

namespace People_Power.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly IRoleRepository _roleRepository;
        public RoleController(IRoleRepository roleRepository)
        {
            _roleRepository = roleRepository;
        }
        public async Task<IActionResult> RoleList()
        {
            var roles = await _roleRepository.GetAllRolesAsync();
            return View(roles);
        }
        [HttpGet]
        public IActionResult CreateRoles()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRoles(Role role)
        {
            if (ModelState.IsValid)
            {
                await _roleRepository.AddRoleAsync(role);
                TempData["SuccessMessage"] = "Role created successfully!";
            }
            return RedirectToAction("RoleList");
        }
    }
}

People_Power/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using People_Power.Interfaces;
using People_Power.ViewModel;

namespace People_Power.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IRoleRepository _roleRepository;
        public UserController(IUserRepository userRepository, IRoleRepository roleRepository)
        {
            _userRepository = userRepository;
            _roleRepository = roleRepository;
        }

        public async Task<IActionResult> AssignRole(int userId)
        {
            var user = await _userRepository.GetUserByIdAsync(userId);
            if (user == null)
            {
                return NotFound();
            }
            var roles = await _roleRepository.GetAllRolesAsync();
            var model = new AssignRoleViewModel
            {
                UserId = userId,
                UserName = user.UserName,
                AvailableRoles = roles,
                CurrentRoleId = user.RoleId
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AssignRole(AssignRoleViewModel model)
        {
            var result = await _userRepository.AssignRoleAsync(model.UserId, model.RoleId);
            if (result != null)
            {
                TempData["SuccessMessage"] = "Role assigned successfully!";
            }
            return RedirectToAction("UserList");
        }
        public async Task<IActionResult> UserList()
        {
            var users = await _userRepository.GetAllUsersAsync();
            return View(users);
        }
    }
}

People_Power/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - People_Power</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/People_Power.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">People_Power</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="CreateRoles">Add Role</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="RoleList">Role List</a>
                        </li>      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmpCreate">Create Employee</a>
                        </li>
                      @*   <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmpCreate">Create Employee</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Payroll" asp-action="PrCreate">Create Payroll</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Leave" asp-action="CreateLeave">Create Leave Appliactions</a></li>
                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Attendance" asp-action="AttdnceCreate">Create Attendance</a></li>                        
                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="UserList">User List</a></li>

                        @* <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="AssignRole">Assign Role</a></li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - People_Power - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>